services:
  portainer:
    container_name: portainer
    image: 'portainer/portainer-ee:latest'
    ports:
      - 9000:9000
      - 9443:9443
    volumes:
      - /pettan/env:/etc/.env:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /pettan/data/portainer:/data
